# Site settings
title: "Victor Ng Curriculum Vitae"
description: "Updated as of 16 Jan 2022"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Ng Thuan Zhian (Victor)"
resume_title:                   "Salesforce Developer & Consultant based in Singapore"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "victorng8@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+65 9770 9462"
#resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "+65 9770 9462 • victorng8@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>Salesforce specialist with over 5 years working experience in CRM system implementations and Java software development. Trained as a functional consultant and attained multiple Salesforce certifications. Demonstrated success in Salesforce projects with established organizations in the Insurance, Media, Telecommunications, Real Estate and Logistic sectors. Experienced in problem-solving, delivering Salesforce customized solutions and working effectively with numerous project teams to meet project deadlines and manage client expectations.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  #resume_github_url:            "https://github.com/jglovier/resume-template"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
resume_linkedin_url:          "https://www.linkedin.com/in/victortzng"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
